version: '2.0'

services:

  nginx:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/www:/etc/nginx/html
    depends_on:
    - jenkins
    - sonarqube

  jenkins:
    image: jenkins/jenkins:lts-alpine
    environment:
    - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
    - jenkins:/var/jenkins_home

  sonarqube:
    image: sonarqube
    command: -Dsonar.web.context=/sonarqube
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
    - sonarqube:/opt/sonarqube/data
    depends_on:
    - postgres

  postgres:
    image: postgres
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

volumes:
  jenkins:
  sonarqube:
  postgres:

